### ISSUE TITLE
Wrong x- and y-Position in Formula for sun-Angle

### ISSUE THREAD

**Issue by twistios** [scartwright91/pygame-tutorials#1]
I just found your Youtube-Video to 2d shadows in Pygame. I downloaded your code to test it out. I wanted to see, what happens if you have a moving sun. So it put your "shadow-casting-code" inside a function and adjusted the position of the sun. At first I thought it felt strange, because the movement of the shadow did not fit what I expected.

The problematic line of code:
`sun_angle = math.atan2((sun_pos.y - target_pos.y),(sun_pos.x - target_pos.x))`
To fix that problem, I just changed the line to
`sun_angle = math.atan2((sun_pos.x - target_pos.x),(sun_pos.y - target_pos.y))`.

This is just a small, but impacting change, because
1. It now works how it should and
2. doesn't crash for larger values (as far as I can see)

Besides that, I find your video very informative and helpful.

**Comment by scartwright91** [comment]
Wow you're right, I only tested the sun position in the two corners but it seems the angle value is off between these two locations. It's strange because normally it should be `math.atan2(y_delta, x_delta)` but your solution gives the answer we want.

Thanks for spotting this and offering a solution, ill update the code.
